name = "mp4-to-gif-worker"
main = "src/worker.ts"
compatibility_date = "2026-03-24"

[observability.logs]
enabled = true

[build]
command = ""

[[rules]]
type = "CompiledWasm"
globs = ["native/out/*.wasm"]
fallthrough = true
